export const ADD_MOVIE_POST = "ADD_MOVIE_POST";
/*export const DELETE_MOVIE_POST = "DELETE_MOVIE_POST";

export const ADD_CINEMAS_POST = "ADD_CINEMAS_POST";
export const DELETE_CINEMAS_POST = "DELETE_CINEMAS_POST";*/

export const FETCH_MOVIES_POST = "FETCH_MOVIES_POST";
//export const FETCH_CINEMAS_POST = "FETCH_CINEMAS_POST";
