INSERT INTO SHP_USER (SHP_USER_ID, SHP_NAME, SHP_USER_NAME, SHP_USER_EMAIL, SHP_PASSWORD, SHP_ISADMIN)
VALUES  (1, 'Admin User', 'adminUser','user@mail.com', 'password', true);


INSERT INTO PRODUCT (dtype, PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_QTY, PRODUCT_PRICE, Genre, Author, Publications, APP_TYPE, APP_BRAND, APP_DESIGN) VALUES ("Book", 1, 'Wings of Fire', 'An Autobiography of APJ Abdul Kalam', 10, 200, 'AutoBiography', 'APJ Abdul Kalam, Arun Tiwari','Universities Press', null, null, null);
INSERT INTO PRODUCT (dtype, PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_QTY, PRODUCT_PRICE, Genre, Author, Publications, APP_TYPE, APP_BRAND, APP_DESIGN) VALUES ("Book", 2, 'The Harry Potter series', 'Harry Potter Series of Books', 10, 750, 'Fiction', 'J.K. Rowling','Universities Press', null, null, null);
INSERT INTO PRODUCT (dtype, PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_QTY, PRODUCT_PRICE, Genre, Author, Publications, APP_TYPE, APP_BRAND, APP_DESIGN) VALUES ("Book", 3, 'The Lord of the Rings Trilogy', 'Complete set of Lord of the Rings', 10, 800, 'Fiction', 'J.R.R. Tolkien','Universities Press', null, null, null);
INSERT INTO PRODUCT (dtype, PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_QTY, PRODUCT_PRICE, Genre, Author, Publications, APP_TYPE, APP_BRAND, APP_DESIGN) VALUES ("Book", 4, 'A Game of Thrones', 'Game of Thrones', 10, 500, 'Fiction', 'George R.R. Martin','Universities Press', null, null, null);
INSERT INTO PRODUCT (dtype, PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_QTY, PRODUCT_PRICE, Genre, Author, Publications, APP_TYPE, APP_BRAND, APP_DESIGN) VALUES ("Book", 5, 'The Alchemist', 'Paulo Coelho masterpiece tells the magical story', 10, 250, 'Fiction', 'Paulo Coelho','Universities Press', null, null, null);
INSERT INTO PRODUCT (dtype, PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_QTY, PRODUCT_PRICE, Genre, Author, Publications, APP_TYPE, APP_BRAND, APP_DESIGN) VALUES ("Apparal", 6, 'Dickies Boys Short Sleeve Pique Polo', 'Boys Clothing', 10, 135, null, null, null,'Clothing','Dickies','Polo Shirts');
INSERT INTO PRODUCT (dtype, PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_QTY, PRODUCT_PRICE, Genre, Author, Publications, APP_TYPE, APP_BRAND, APP_DESIGN) VALUES ("Apparal", 7, 'Under Armour Boys Prototype Logo Shorts', 'Boys Clothing', 5, 500, null, null, null,'Clothing','Under Armour','Prototype Logo Shorts');
INSERT INTO PRODUCT (dtype, PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_QTY, PRODUCT_PRICE, Genre, Author, Publications, APP_TYPE, APP_BRAND, APP_DESIGN) VALUES ("Apparal", 8, 'Originals Kids Superstar Sneaker', 'adidas kids shoes', 20, 200, null, null, null,'Shoes','adidas Originals','Kids Shoes');
INSERT INTO PRODUCT (dtype, PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_QTY, PRODUCT_PRICE, Genre, Author, Publications, APP_TYPE, APP_BRAND, APP_DESIGN) VALUES ("Apparal", 9, 'Gerber Baby 5-Pack Solid Onesies Bodysuits', 'Baby Girls Bodysuits', 25, 450, null, null, null,'Baby Bodysuits','Gerber','suits');
INSERT INTO PRODUCT (dtype, PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_QTY, PRODUCT_PRICE, Genre, Author, Publications, APP_TYPE, APP_BRAND, APP_DESIGN) VALUES ("Apparal", 10, 'Baby Girls Top and Pant Set', 'Tunic and Leggings Bundle, 100% Organic Cotton', 50, 300, null, null, null,'Baby Top and Pant','Burts Bees Baby','Girls Top and Pant');
INSERT INTO PRODUCT (dtype, PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_QTY, PRODUCT_PRICE, Genre, Author, Publications, APP_TYPE, APP_BRAND, APP_DESIGN) VALUES ("Apparal", 11, 'Cotton Full Sleeve Hooded T-Shirt', 'Cotton Full Sleeve - Small size', 50, 346, null, null, null,'Mens T-shirt','SHAUN','Hooded T-Shirt');
INSERT INTO PRODUCT (dtype, PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_QTY, PRODUCT_PRICE, Genre, Author, Publications, APP_TYPE, APP_BRAND, APP_DESIGN) VALUES ("Book", 12, 'Tamil with 101 Moral Stories', 'Story Books set of 10 in Tamil', 10, 270, 'Study Children', 'Multiple Authors','Universities Press', null, null, null);
INSERT INTO PRODUCT (dtype, PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_QTY, PRODUCT_PRICE, Genre, Author, Publications, APP_TYPE, APP_BRAND, APP_DESIGN) VALUES ("Apparal", 13, 'Synthetic Slide', 'Sole: polyvinyl chloride', 50, 300, null, null, null,'Synthetic Slide SL5137 Slippers','Kraasa','Slippers');
INSERT INTO PRODUCT (dtype, PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_QTY, PRODUCT_PRICE, Genre, Author, Publications, APP_TYPE, APP_BRAND, APP_DESIGN) VALUES ("Book", 14, 'Animals Tales From Panchtantra', 'Timeless Stories For Children From Ancient India', 10, 169, 'Study Children', 'Wonder House Books (Author)','Universities Press', null, null, null);
INSERT INTO PRODUCT (dtype, PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_QTY, PRODUCT_PRICE, Genre, Author, Publications, APP_TYPE, APP_BRAND, APP_DESIGN) VALUES ("Apparal", 15, 'Synthetic Leather Boots', 'Synthetic Leather Boots', 50, 300, null, null, null,'Leather Boots','BKraasa','Boots');
INSERT INTO PRODUCT (dtype, PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_QTY, PRODUCT_PRICE, Genre, Author, Publications, APP_TYPE, APP_BRAND, APP_DESIGN) VALUES ("Book", 16, 'Malgudi Adventures', 'Adventures in Malgudi', 10, 180, 'Fictiom', 'Narayan R.K. (Author)','PTI', null, null, null);
INSERT INTO PRODUCT (dtype, PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_QTY, PRODUCT_PRICE, Genre, Author, Publications, APP_TYPE, APP_BRAND, APP_DESIGN) VALUES ("Apparal", 17, 'MENS-BLACK-THUMBCUT-ZIPPER-SPORTS-T-SHIRT-02', 'ZIPPER-SPORTS-T-SHIRT', 50, 300, null, null, null,'ZIPPER-SPORTS-T-SHIRT','WC RIGHT','ZIPPER-SPORTS-T-SHIRT');
INSERT INTO PRODUCT (dtype, PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_QTY, PRODUCT_PRICE, Genre, Author, Publications, APP_TYPE, APP_BRAND, APP_DESIGN) VALUES ("Book", 18, 'Wooden Tamil Alphabet/Letters Cut Outs', 'Cryo Craft Plain Laser Cut Wooden Tamil Alphabet/Letters Cut Outs', 10, 200, 'Cryo Craft', 'Cryo Craft','Cryo Craft', null, null, null);
INSERT INTO PRODUCT (dtype, PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_QTY, PRODUCT_PRICE, Genre, Author, Publications, APP_TYPE, APP_BRAND, APP_DESIGN) VALUES ("Apparal", 19, 'Plain Regular Fit T-Shirt', 'Crew neck sleeve less tee with contrast panels at front & back- 60% Cotton and 40% Polyester', 50, 499, null, null, null,'T-shirt','Chromozome','T-shirt');
INSERT INTO PRODUCT (dtype, PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_QTY, PRODUCT_PRICE, Genre, Author, Publications, APP_TYPE, APP_BRAND, APP_DESIGN) VALUES ("Book", 20, 'Tamil alphabets with pictures', 'Tamil alphabets with pictures to Tamil reading fluency ', 10, 200, 'Study', 'Lilliput','Lilliput Tamil Flash cards', null, null, null);